name: "TokenRemover-test"
url: https://github.com/MennovH/HomeAssistant/tree/main/TokenRemover-test
description: "Add-on for Home Assistant to remove old refresh tokens"
codenotary: mennovh_@hotmail.com
version: "1.0.5"
slug: "tokenremover-test"
hassio_api: true
auth_api: true
hassio_role: manager
apparmor: false
ingress: false
# ingress: true
# ingress_port: 0
# ingress_stream: true
boot: manual
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
journald: true
panel_icon: mdi:update
options:
  retention_days: 7
  keep_active: true
  activation_days: 7
  am_pm: "Night"
  automation_time: "03:00 \/ 15:00"
  mon: true
  tue: true
  wed: true
  thu: true
  fri: true
  sat: true
  sun: true
schema:
  retention_days: int(0,365)
  keep_active: bool
  activation_days: int(1,365)
  am_pm: list(Night|Day|Both)
  automation_time: list(0:00 and/or 12:00|0:15 and/or 12:15|0:30 and/or 12:30|0:45 and/or 12:45|1:00 and/or 13:00|1:15 and/or 13:15|1:30 and/or 13:30|1:45 and/or 13:45|2:00 and/or 14:00|2:15 and/or 14:15|2:30 and/or 14:30|2:45 and/or 14:45|3:00 and/or 15:00|3:15 and/or 15:15|3:30 and/or 15:30|3:45 and/or 15:45|4:00 and/or 16:00|4:15 and/or 16:15|4:30 and/or 16:30|4:45 and/or 16:45|5:00 and/or 17:00|5:15 and/or 17:15|5:30 and/or 17:30|5:45 and/or 17:45|6:00 and/or 18:00|6:15 and/or 18:15|6:30 and/or 18:30|6:45 and/or 18:45|7:00 and/or 19:00|7:15 and/or 19:15|7:30 and/or 19:30|7:45 and/or 19:45|8:00 and/or 20:00|8:15 and/or 20:15|8:30 and/or 20:30|8:45 and/or 20:45|9:00 and/or 21:00|9:15 and/or 21:15|9:30 and/or 21:30|9:45 and/or 21:45|10:00 and/or 22:00|10:15 and/or 22:15|10:30 and/or 22:30|10:45 and/or 22:45|11:00 and/or 23:00|11:15 and/or 23:15|11:30 and/or 23:30|11:45 and/or 23:45)
  mon: bool
  tue: bool
  wed: bool
  thu: bool
  fri: bool
  sat: bool
  sun: bool
startup: application
