name: "TokenRemover-test"
url: https://github.com/MennovH/HomeAssistant/tree/main/TokenRemover
description: "Add-on for Home Assistant to remove old refresh tokens"
codenotary: mennovh_@hotmail.com
version: "1.0.5"
slug: "tokenremover-test"
hassio_api: true
auth_api: true
hassio_role: manager
apparmor: false
ingress: false
# ingress: true
# ingress_port: 0
# ingress_stream: true
boot: manual
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
journald: true
panel_icon: mdi:update
options:
  retention_days: 7
  keep_active: true
  activation_days: 7
  am_pm: "AM"
  automation_time: "03:00"
  mon: true
  tue: true
  wed: true
  thu: true
  fri: true
  sat: true
  sun: true
schema:
  retention_days: int(0,365)
  keep_active: bool
  activation_days: int(1,365)
  am_pm: list(AM|PM|Both)
  automation_time: list(0:00 / 12:00|0:15 / 12:15|0:30 / 12:30|0:45 / 12:45|1:00 / 13:00|1:15 / 13:15|1:30 / 13:30|1:45 / 13:45|2:00 / 14:00|2:15 / 14:15|2:30 / 14:30|2:45 / 14:45|3:00 / 15:00|3:15 / 15:15|3:30 / 15:30|3:45 / 15:45|4:00 / 16:00|4:15 / 16:15|4:30 / 16:30|4:45 / 16:45|5:00 / 17:00|5:15 / 17:15|5:30 / 17:30|5:45 / 17:45|6:00 / 18:00|6:15 / 18:15|6:30 / 18:30|6:45 / 18:45|7:00 / 19:00|7:15 / 19:15|7:30 / 19:30|7:45 / 19:45|8:00 / 20:00|8:15 / 20:15|8:30 / 20:30|8:45 / 20:45|9:00 / 21:00|9:15 / 21:15|9:30 / 21:30|9:45 / 21:45|10:00 / 22:00|10:15 / 22:15|10:30 / 22:30|10:45 / 22:45|11:00 / 23:00|11:15 / 23:15|11:30 / 23:30|11:45 / 23:45)
  mon: bool
  tue: bool
  wed: bool
  thu: bool
  fri: bool
  sat: bool
  sun: bool
startup: application
