name: "RouteHA-notfunctional"
url: https://github.com/MennovH/HomeAssistant/tree/main/RouteHA
description: "Add-on to configure the desired routes for Home Assistant"
codenotary: mennovh_@hotmail.com
version: "1.0.0"
slug: "routeha"
ingress: false
auth_api: true
apparmor: false
hassio_role: manager
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
journald: true
panel_icon: mdi:directions
options:
  gateway: null
  static_routes: []
  interval: 10
schema:
  gateway: str
  static_routes:
    - "str?"
  interval: int(1,1440)
