name: "CloudflareDDNS"
url: https://github.com/MennovH/HomeAssistant/tree/main/CloudflareDDNS
description: "Cloudflare DDNS add-on for Home Assistant"
codenotary: mennovh_@hotmail.com
version: "1.3.6"
slug: "cloudflareddns"
ingress: false
apparmor: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:cloud-check
options:
  cloudflare_zone_id: null
  cloudflare_api_token: null
  interval: 10
  hide_public_ip: true
  domains: []
schema:
  cloudflare_zone_id: password
  cloudflare_api_token: password
  interval: int(1,1440)
  hide_public_ip: bool
  domains:
    - "str?"
