name: "CloudflareDDNS"
url: https://github.com/MennovH/CloudflareDDNS
description: "Cloudflare DDNS add-on for Home Assistant"
codenotary: cas.mennovh@gmail.com
version: "1.3.0"
slug: "cloudflareddns"
ingress: false
apparmor: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:cloud-check
options:
  email_address: null
  cloudflare_zone_id: null
  cloudflare_api_token: null
  domains:
    - domain: null
  interval: 15
  hide_public_ip: true
  sort: true
schema:
  email_address: email
  cloudflare_zone_id: password
  cloudflare_api_token: password
  domains:
    - domain: str
  interval: int(1,1440)
  hide_public_ip: bool
  sort: bool
