name: "CloudflareDDNS"
url: https://github.com/MennovH/CloudflareDDNS
description: "Cloudflare DDNS add-on for Home Assistant"
codenotary: cas.mennovh@gmail.com
version: "1.2.2"
slug: "ddns"
ingress: false
apparmor: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:cloud-check
options:
  E-mail address: null
  Cloudflare Zone ID: null
  Cloudflare API token: null
  (sub)Domains:
    - domain: null
  Time interval: 15
  Show public IP: true
  Sort domains alphabetically: true
schema:
  E-mail address: email
  Cloudflare Zone ID: password
  cloudflare_api_token: password
  domains:
    - domain: str
  Time interval: int(1,1440)
  Show public IP: bool
  Sort domains alphabetically: bool
