name: "CloudflareDDNS"
url: https://github.com/MennovH/CloudflareDDNS
description: "Cloudflare DDNS add-on for Home Assistant"
codenotary: cas.mennovh@gmail.com
version: "1.2.2"
slug: "ddns"
ingress: false
apparmor: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:cloud-check
options:
  email_address: null
  cloudflare_zone_id: null
  cloudflare_api_token: null
  domains: {}
  interval: 15
schema:
  email_address: email
  cloudflare_zone_id: password
  cloudflare_api_token: password
  domains:
    - str
  interval: int(1,1440)
