name: "CFWAFUpdater"
url: https://github.com/MennovH/HomeAssistant/tree/main/CFWAFUpdater
description: "Cloudflare WAF rule updater add-on for Home Assistant"
#codenotary: mennovh_@hotmail.com
version: "0.0.1"
slug: "CFWAFUpdater"
ingress: false
auth_api: true
apparmor: false
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
journald: true
panel_icon: mdi:cloud-check
options:
  cloudflare_zone_id: null
  cloudflare_api_token: null
  waf_ruleset_id: null
  waf_rule_id: null
  waf_rule_expression: null
  interval: 10
  log_pip: true
  
schema:
  cloudflare_zone_id: password
  cloudflare_api_token: password
  waf_ruleset_id: password
  waf_rule_id: password
  waf_rule_expression: str
  interval: int(1,1440)
  log_pip: bool
  
