name: "FallbackHTTP"
url: https://github.com/MennovH/FallbackHTTP
description: "HTTP fallback for Home Assistant"
#codenotary: cas.mennovh@gmail.com
version: "1.0.1"
slug: "fallbackhttp"
ingress: false
apparmor: true
init: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:cloud-check
options:
  internal_ip_or_fqdn: null
  internal_port: null
  test_method:
    - "Certificate"
    - "Connection"
  interval: 15
schema:
  internal_ip: str
  internal_port: int
  test_method:
    - str
    - str
  interval: int(1,1440)
