name: "IPBan"
url: https://github.com/MennovH/HomeAssistant/tree/main/IPBan
description: "IPBan add-on for Home Assistant"
#codenotary: cas.mennovh@gmail.com
version: "1.0.0"
slug: "ipban"
ingress: false
apparmor: true
init: false
map:
  - config:rw
  - usr/share/hassio:r
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:allow
options:
  interval: 1
  allow: false
schema:
  interval: int(1,1440)
  allow: bool
