name: "Unban"
url: https://github.com/MennovH/HomeAssistant/tree/main/Unban
description: "Unban add-on for Home Assistant"
codenotary: mennovh_@hotmail.com
version: "1.0.0"
slug: "unban"
hassio_api: true
auth_api: true
hassio_role: manager
apparmor: false
ingress: false
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
startup: application
journald: true
panel_icon: mdi:account-lock-open
options:
  interval: 5
  ip: []
schema:
  interval: int(1,1440)
  ip: 
    - "str"
