name: "TokenRemover"
url: https://github.com/MennovH/HomeAssistant/tree/main/TokenRemover
description: "Add-on for Home Assistant to remove old refresh tokens"
#codenotary: mennovh_@hotmail.com
version: "1.0.0"
slug: "tokenremover"
ingress: false
apparmor: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:update
options:
  hour: 00
  quarter: 00
  day: 7
schema:
  hour: list(00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23)
  quarter: list(00|15|30|45)
  day: int(1,365)
