name: "CloudflareDDNS"
description: "Cloudflare DDNS addon"
version: "1.1.6"
slug: "ddns"
ingress: true
apparmor: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
journald: true
panel_icon: mdi:cloud-check
options:
  email_address: ""
  cloudflare_zone_id: ""
  cloudflare_api_token: ""
  domains: []
  interval: 15
schema:
  email_address: str
  cloudflare_zone_id: str
  cloudflare_api_token: password
  domains:
    - str
  interval: int(1,1440)
